#pragma once

// -----------------------------------------------------------------------------
// Ubiquitous CPU-trace instrumentation surface (final design §9, §18, §22).
//
// This is THE header included across the engine, so it is deliberately cheap:
// it pulls in only <ludus/foundation/profiling/zone.hpp> (string_view +
// source_location, and the fixed-width types via <ludus/foundation/base/types.h>),
// <ludus/foundation/base/compiler.h> for LUDUS_INLINE (Band 0 macros only, no
// code), and <atomic> for the fast-path gate, plus the shared clock
// declaration. It deliberately does NOT pull the full core.h (which would add
// the assertion plumbing) — it includes exactly the Band 0 pieces it uses. It
// contains NO <chrono>, <format>, <string>, <vector>, iostreams,
// and instantiates no heavy templates — all real logic is type-erased behind
// non-template `detail::` functions compiled once in profiling.cpp (ADR 0004,
// build-time gate G8).
//
// Six orthogonal concepts (§22): SCOPE, FUNCTION, FRAME, MARK, FLOW, (GPU later).
// Counters/gauges are a separate subsystem (Phase 2) and intentionally not here.
//
// Compile-out (gate C7/G1): when LUDUS_PROFILING_ENABLED == 0 every macro
// expands to `((void)0)` and NO argument is evaluated. When enabled, an idle
// (no active capture) site costs one relaxed atomic load + a predicted-not-taken
// branch and nothing else (§19, G2).
// -----------------------------------------------------------------------------

#include <ludus/foundation/base/compiler.h>
#include <ludus/foundation/profiling/clock.hpp>
#include <ludus/foundation/profiling/zone.hpp>

// SDK-owned enable flag. The generated header defines it; the fallback keeps the
// header usable when compiled standalone (e.g. a micro-benchmark TU that sets it
// explicitly). Never predefine it in engine code — see profiling_config.hpp.in.
#if defined(__has_include)
#    if __has_include(<ludus/foundation/profiling/profiling_config.hpp>)
#        include <ludus/foundation/profiling/profiling_config.hpp>
#    endif
#endif
#if !defined(LUDUS_PROFILING_ENABLED)
#    define LUDUS_PROFILING_ENABLED 0
#endif

namespace ludus::foundation::profiling
{

namespace detail
{

// Type-erased hot-path entry points (compiled once in profiling.cpp). Each is a
// thin, non-template noexcept function so the ubiquitous header stays template-
// and dependency-free. All are no-ops (single relaxed load + branch) when no
// capture is active.
void EmitBegin(const ZoneDescriptor& descriptor) noexcept;
void EmitEnd(uint32 siteId) noexcept;
void EmitInstant(const ZoneDescriptor& descriptor) noexcept;
void EmitFrameMark() noexcept;
[[nodiscard]] uint64 EmitFlowOut(const ZoneDescriptor& descriptor) noexcept;
void EmitFlowIn(uint64 flowId) noexcept;

// One-time site registration: records the descriptor's id -> name/file/line in
// the process ZoneRegistry so the exporter can resolve names without carrying
// strings in events (§13/§14). Guarded per site by a function-local static bool
// generated by the macro, so the registry write happens at most once per site,
// off the per-hit path.
void RegisterSite(const ZoneDescriptor& descriptor) noexcept;

// Fast-path predicate: true only while a capture session is active. A single
// relaxed atomic load, safe before Initialize(), no allocation. Lets the RAII
// ctor/dtor and macros skip all work when idle without touching the recorder.
[[nodiscard]] bool CaptureActive() noexcept;

} // namespace detail

// RAII scope. ctor emits Begin, dtor emits End (paired within the thread — C5).
// Non-template, trivially small. The End reuses the site id so the dtor does not
// re-read the descriptor. Guaranteed to fire on early return (there are no
// exceptions under -fno-exceptions). Copy/move deleted so an event is never
// emitted twice or dropped.
class ScopedZone
{
public:
    LUDUS_INLINE explicit ScopedZone(const ZoneDescriptor& descriptor) noexcept : mSiteId(descriptor.SiteId)
    {
        detail::EmitBegin(descriptor);
    }

    LUDUS_INLINE ~ScopedZone() noexcept
    {
        detail::EmitEnd(mSiteId);
    }

    ScopedZone(const ScopedZone&) = delete;
    ScopedZone& operator=(const ScopedZone&) = delete;
    ScopedZone(ScopedZone&&) = delete;
    ScopedZone& operator=(ScopedZone&&) = delete;

private:
    uint32 mSiteId;
};

} // namespace ludus::foundation::profiling

// -----------------------------------------------------------------------------
// Macro surface.
// -----------------------------------------------------------------------------
#define LUDUS_PROFILE_DETAIL_CONCAT_(a, b) a##b
#define LUDUS_PROFILE_DETAIL_CONCAT(a, b) LUDUS_PROFILE_DETAIL_CONCAT_(a, b)
#define LUDUS_PROFILE_DETAIL_UNIQUE(prefix) LUDUS_PROFILE_DETAIL_CONCAT(prefix, __LINE__)

#if LUDUS_PROFILING_ENABLED

// Register a site at most once (off the per-hit path): a function-local static
// bool flips on first execution and calls RegisterSite. `desc` must be a stable
// (static constexpr) descriptor.
#    define LUDUS_PROFILE_DETAIL_REGISTER_ONCE(desc)                                                                   \
        do                                                                                                             \
        {                                                                                                              \
            static bool LUDUS_PROFILE_DETAIL_UNIQUE(ludus_reg_) = false;                                               \
            if (!LUDUS_PROFILE_DETAIL_UNIQUE(ludus_reg_))                                                              \
            {                                                                                                          \
                LUDUS_PROFILE_DETAIL_UNIQUE(ludus_reg_) = true;                                                        \
                ::ludus::foundation::profiling::detail::RegisterSite(desc);                                            \
            }                                                                                                          \
        } while (false)

// Overload plumbing so LUDUS_PROFILE_SCOPE accepts (name) or (name, category).
#    define LUDUS_PROFILE_DETAIL_SCOPE1(name)                                                                          \
        static constexpr ::ludus::foundation::profiling::ZoneDescriptor LUDUS_PROFILE_DETAIL_UNIQUE(ludus_zone_desc_){ \
            ::std::string_view{#name}};                                                                                \
        LUDUS_PROFILE_DETAIL_REGISTER_ONCE(LUDUS_PROFILE_DETAIL_UNIQUE(ludus_zone_desc_));                             \
        const ::ludus::foundation::profiling::ScopedZone LUDUS_PROFILE_DETAIL_UNIQUE(ludus_zone_)                      \
        {                                                                                                              \
            LUDUS_PROFILE_DETAIL_UNIQUE(ludus_zone_desc_)                                                              \
        }

#    define LUDUS_PROFILE_DETAIL_SCOPE2(name, category)                                                                \
        static constexpr ::ludus::foundation::profiling::ZoneDescriptor LUDUS_PROFILE_DETAIL_UNIQUE(                   \
            ludus_zone_desc_){::std::string_view{#name}, (category)};                                                  \
        LUDUS_PROFILE_DETAIL_REGISTER_ONCE(LUDUS_PROFILE_DETAIL_UNIQUE(ludus_zone_desc_));                             \
        const ::ludus::foundation::profiling::ScopedZone LUDUS_PROFILE_DETAIL_UNIQUE(ludus_zone_)                      \
        {                                                                                                              \
            LUDUS_PROFILE_DETAIL_UNIQUE(ludus_zone_desc_)                                                              \
        }

#    define LUDUS_PROFILE_DETAIL_SCOPE_PICK(_1, _2, NAME, ...) NAME

// 1. CPU scope. `name` is a bare identifier token, stringised once at compile
//    time; it is never evaluated as an expression (§9). Optional 2nd arg is a
//    ProfileCategory.
#    define LUDUS_PROFILE_SCOPE(...)                                                                                   \
        LUDUS_PROFILE_DETAIL_SCOPE_PICK(__VA_ARGS__, LUDUS_PROFILE_DETAIL_SCOPE2, LUDUS_PROFILE_DETAIL_SCOPE1)         \
        (__VA_ARGS__)

// 2. Function scope. Name derived from source_location at compile time.
// __func__ is not a constant expression, so FUNCTION builds its descriptor at
// runtime (still trivial: two string_view assignments) rather than constexpr.
// Registration still happens once per site.
#    define LUDUS_PROFILE_FUNCTION()                                                                                   \
        const ::ludus::foundation::profiling::ZoneDescriptor LUDUS_PROFILE_DETAIL_UNIQUE(ludus_fn_desc_){              \
            ::std::string_view{static_cast<const char*>(__func__)}};                                                   \
        LUDUS_PROFILE_DETAIL_REGISTER_ONCE(LUDUS_PROFILE_DETAIL_UNIQUE(ludus_fn_desc_));                               \
        const ::ludus::foundation::profiling::ScopedZone LUDUS_PROFILE_DETAIL_UNIQUE(ludus_fn_zone_)                   \
        {                                                                                                              \
            LUDUS_PROFILE_DETAIL_UNIQUE(ludus_fn_desc_)                                                                \
        }

// 3. Frame marker. Advances the frame epoch (not a reset — D7).
#    define LUDUS_PROFILE_FRAME() ::ludus::foundation::profiling::detail::EmitFrameMark()

// 4. Instant marker. Zero-duration annotation.
#    define LUDUS_PROFILE_MARK(name)                                                                                   \
        do                                                                                                             \
        {                                                                                                              \
            static constexpr ::ludus::foundation::profiling::ZoneDescriptor ludus_mark_desc_{                          \
                ::std::string_view{#name}};                                                                            \
            static bool ludus_mark_reg_ = false;                                                                       \
            if (!ludus_mark_reg_)                                                                                      \
            {                                                                                                          \
                ludus_mark_reg_ = true;                                                                                \
                ::ludus::foundation::profiling::detail::RegisterSite(ludus_mark_desc_);                                \
            }                                                                                                          \
            ::ludus::foundation::profiling::detail::EmitInstant(ludus_mark_desc_);                                     \
        } while (false)

// 5. Flow. FLOW_OUT returns a correlation id; FLOW_IN consumes it. The primitive
//    is live now; the scheduler stamping that uses it lands with the job system.
//    FLOW_OUT is an expression (yields the id); a helper carries the descriptor.
#    define LUDUS_PROFILE_FLOW_OUT(name)                                                                               \
        ::ludus::foundation::profiling::detail::EmitFlowOut(                                                           \
            ::ludus::foundation::profiling::ZoneDescriptor{::std::string_view{#name}})
#    define LUDUS_PROFILE_FLOW_IN(flow_id) ::ludus::foundation::profiling::detail::EmitFlowIn((flow_id))

#else // LUDUS_PROFILING_ENABLED == 0 : compile out with NO argument evaluation.

#    define LUDUS_PROFILE_SCOPE(...) ((void)0)
#    define LUDUS_PROFILE_FUNCTION() ((void)0)
#    define LUDUS_PROFILE_FRAME() ((void)0)
#    define LUDUS_PROFILE_MARK(name) ((void)0)
#    define LUDUS_PROFILE_FLOW_OUT(name) (static_cast<::ludus::foundation::uint64>(0))
#    define LUDUS_PROFILE_FLOW_IN(flow_id) ((void)0)

#endif // LUDUS_PROFILING_ENABLED
