"""Shared inventory of canonical authored documentation and its local index."""
from hashlib import sha256
from pathlib import Path

# Doxygen's input landing page is rendered by the API generator, not as a guide.
EXCLUDED_MARKDOWN = {"api-main.md"}
INDEX = "README.md"
GROUPS = (
    "Start and orientation", "Guides and workflows", "Module usage",
    "Examples and probes", "Architecture and design", "Decisions",
    "Research and reviews", "Plans and handoffs", "Validation and evidence",
    "Historical baselines", "Earlier entry points",
)


def sources(root):
    return sorted(path for path in (root / "docs").rglob("*.md")
                  if path.relative_to(root / "docs").as_posix() not in EXCLUDED_MARKDOWN)


def digest(path):
    return sha256(path.read_bytes()).hexdigest()


def title(path):
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ")


def group(relative):
    """Classify a document's role, without claiming its proposal is implemented."""
    name, parts = relative.stem, relative.parts
    if relative.as_posix() in {"wiki/contribute/wiki.md", "wiki/contribute/api-reference.md",
                                "wiki/guides/editor.md", "wiki/guides/project-setup.md", "wiki/guides/releases.md"}:
        return "Earlier entry points"
    if relative.as_posix() == "architecture/profiling.md" or name in {"milestone-0", "milestone-1", "milestone-2"}:
        return "Historical baselines"
    if any("evidence" in part for part in parts) or name.endswith(("-validation", "-performance", "-decision-log")):
        return "Validation and evidence"
    if name in {"assertions-m0-m1", "luau-s0", "luau-s1", "memory-phase-0a", "webgpu-hosted-acceptance"} or name.startswith("webgpu-w"):
        return "Validation and evidence"
    if name.endswith(("-handoff", "-milestones", "-implementation-plan", "-development-plan")):
        return "Plans and handoffs"
    if name.endswith(("-review", "-research", "-reading-guide")):
        return "Research and reviews"
    if parts[0] == "decisions":
        return "Decisions"
    if parts[0] == "modules":
        return "Module usage"
    if parts[0] == "examples" or parts[:2] == ("development", "tools"):
        return "Examples and probes"
    if parts[0] == "architecture":
        return "Architecture and design"
    if parts[0] == "development" or parts[:2] == ("wiki", "guides"):
        return "Guides and workflows"
    return "Start and orientation"


def index_text(root):
    lines = [
        "# Ludus documentation", "",
        "These Markdown files are the sources rendered by Ludus Wiki. Open this",
        "directory in VS Code, Obsidian, another Markdown reader or a text editor.",
        "Relative links and local images work without internet access.", "",
        "## Document roles", "",
        "Guides describe supported workflows. Module pages contain usage examples.",
        "Designs can contain proposed extensions; read their status and evidence.",
        "Reviews record consulted sources, plans record intended work, and validation",
        "records name the tested revision and environment. Historical baselines retain",
        "earlier decisions and boundaries. Their statements apply to that scope.", "",
        "The inventory below covers every authored page, grouped by its role.",
        "It is generated by `python scripts/check-docs --fix-index`; edit linked pages",
        "for content changes. Module/sample/tool READMEs link to these owners.", "",
    ]
    quick = (
        ("Install and launch the editor", "wiki/getting-started/install.md"),
        ("Build the engine: native, headless, container and macOS", "development/building.md"),
        ("Create your first game", "wiki/getting-started/first-project.md"),
        ("Use the CLI and shared SDKs", "development/project-sdk-workflow.md"),
        ("Explore current capabilities", "wiki/getting-started/status.md"),
        ("Find the architecture owner", "wiki/architecture/index.md"),
        ("Read or package documentation offline", "development/wiki.md#offline-reading"),
    )
    available = [(label, target) for label, target in quick
                 if (root / "docs" / target.split("#")[0]).is_file()]
    if available:
        lines[6:6] = ["", "## Choose a task", "", *[f"- [{label}]({target})" for label, target in available], ""]
    grouped = {label: [] for label in GROUPS}
    for path in sources(root):
        relative = path.relative_to(root / "docs")
        if relative.as_posix() != INDEX:
            grouped[group(relative)].append((path, relative.as_posix()))
    for label, items in grouped.items():
        if not items:
            continue
        lines.extend(["## " + label, ""])
        for path, relative in sorted(items, key=lambda item: (title(item[0]).casefold(), item[1])):
            text = title(path).replace("[", "\\[").replace("]", "\\]")
            lines.append(f"- [{text}]({relative})")
        lines.append("")
    return "\n".join(lines)
