"""Shared inventory of canonical authored documentation and its local index."""
from hashlib import sha256
from pathlib import Path

# Doxygen's input landing page is rendered by the API generator, not as a guide.
EXCLUDED_MARKDOWN = {"api-main.md"}
INDEX = "README.md"


def sources(root):
    return sorted(path for path in (root / "docs").rglob("*.md")
                  if path.relative_to(root / "docs").as_posix() not in EXCLUDED_MARKDOWN)


def digest(path):
    return sha256(path.read_bytes()).hexdigest()


def title(path):
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ")


def index_text(root):
    lines = [
        "# Ludus documentation", "",
        "These Markdown files are the sources rendered by Ludus Wiki. Open this",
        "directory in VS Code, Obsidian, another Markdown reader or a text editor.",
        "Relative links and local images work without internet access. Start with",
        "[the task guides](wiki/index.md) or [building Ludus](development/building.md).",
        "For browser reading and an offline bundle, see",
        "[documentation tooling](development/wiki.md#offline-reading).", "",
        "This navigation index is generated by `python scripts/check-docs --fix-index`.",
        "Edit the linked documents for content changes.", "",
    ]
    groups = {}
    for path in sources(root):
        relative = path.relative_to(root / "docs")
        if relative.as_posix() != INDEX:
            groups.setdefault(relative.parts[0], []).append((path, relative.as_posix()))
    for group, items in sorted(groups.items()):
        lines.extend(["## " + group.replace("-", " ").capitalize(), ""])
        for path, relative in items:
            label = title(path).replace("[", "\\[").replace("]", "\\]")
            lines.append(f"- [{label}]({relative})")
        lines.append("")
    return "\n".join(lines)
