# S6 build admission, not proof of platform/device qualification. Shared by the
# producer and relocated consumers; never bypassed by the generic SDK override.
include_guard(GLOBAL)
function(ludus_behavior_admit_profile policy output)
    file(READ "${policy}" document)
    string(JSON version GET "${document}" version)
    string(JSON execution GET "${document}" execution)
    if(NOT version EQUAL 1 OR NOT execution STREQUAL "interpreter")
        message(FATAL_ERROR "Unsupported Behavior admission policy")
    endif()
    string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" architecture)
    if(CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND CMAKE_OSX_ARCHITECTURES)
        list(LENGTH CMAKE_OSX_ARCHITECTURES architecture_count)
        if(NOT architecture_count EQUAL 1)
            message(FATAL_ERROR "Behavior requires one declared target architecture per SDK")
        endif()
        string(TOLOWER "${CMAKE_OSX_ARCHITECTURES}" architecture)
    endif()
    if(architecture MATCHES "^(aarch64|arm64)$")
        set(architecture arm64)
    elseif(architecture MATCHES "^(amd64|x86_64)$")
        set(architecture x86_64)
    endif()
    if(CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
        if(NOT EMSCRIPTEN OR NOT CMAKE_SIZEOF_VOID_P EQUAL 4)
            message(FATAL_ERROR "Behavior requires the pinned wasm32 Emscripten profile")
        endif()
        set(architecture wasm32)
    elseif(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
        message(FATAL_ERROR "Behavior native profiles require 64-bit pointers")
    endif()
    string(JSON count LENGTH "${document}" profiles)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON system GET "${document}" profiles ${index} system)
        if(NOT system STREQUAL CMAKE_SYSTEM_NAME)
            continue()
        endif()
        string(JSON admission GET "${document}" profiles ${index} admission)
        if(NOT admission STREQUAL "qualification")
            message(FATAL_ERROR "Behavior profile ${system} requires an engine backend and device qualification; see docs/architecture/behavior-s6.md")
        endif()
        string(JSON major GET "${document}" profiles ${index} compiler_major)
        if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR
           NOT CMAKE_CXX_COMPILER_VERSION MATCHES "^${major}\\.")
            message(FATAL_ERROR "Behavior requires the declared Clang ${major} interpreter profile, got ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
        endif()
        string(JSON arch_count LENGTH "${document}" profiles ${index} architectures)
        math(EXPR arch_last "${arch_count} - 1")
        foreach(arch_index RANGE 0 ${arch_last})
            string(JSON allowed GET "${document}" profiles ${index} architectures ${arch_index})
            if(allowed STREQUAL architecture)
                set(${output} "${system}-${architecture}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endforeach()
    message(FATAL_ERROR "Behavior has no admitted interpreter profile for ${CMAKE_SYSTEM_NAME}/${architecture}")
endfunction()
