# Host generation emits symbolic C++ for the selected target compiler. No target
# binary runs on the host, and no native layout appears in the manifest.
include_guard(GLOBAL)
function(ludus_generate_reflection)
    cmake_parse_arguments(REFLECT "" "TARGET;SCHEMA;BASELINE" "" ${ARGN})
    if(NOT REFLECT_TARGET OR NOT REFLECT_SCHEMA OR REFLECT_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "ludus_generate_reflection requires TARGET and SCHEMA")
    endif()
    find_package(Python3 3.10 REQUIRED COMPONENTS Interpreter)
    get_filename_component(schema "${REFLECT_SCHEMA}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    get_filename_component(schema_dir "${schema}" DIRECTORY)
    file(READ "${schema}" manifest)
    string(JSON native_header GET "${manifest}" header)
    set(output_dir "${CMAKE_CURRENT_BINARY_DIR}/generated/${REFLECT_TARGET}")
    set(header "${output_dir}/${REFLECT_TARGET}_schema.hpp")
    set(source "${output_dir}/${REFLECT_TARGET}_schema.cpp")
    set(json_source "${output_dir}/${REFLECT_TARGET}_json.cpp")
    set(normalized "${output_dir}/${REFLECT_TARGET}.schema.json")
    set(stamp "${output_dir}/generated.stamp")
    set(generator "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/reflection/generate.py")
    if(NOT EXISTS "${generator}")
        set(generator "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tools/reflection/generate.py")
    endif()
    set(baseline_args)
    set(baseline_dep)
    if(REFLECT_BASELINE)
        get_filename_component(baseline_dep "${REFLECT_BASELINE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        list(APPEND baseline_args --baseline "${baseline_dep}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${schema}")
    add_custom_command(OUTPUT "${stamp}"
        BYPRODUCTS "${header}" "${source}" "${json_source}" "${normalized}"
        COMMAND "${Python3_EXECUTABLE}" "${generator}" --schema "${schema}"
            --header "${header}" --source "${source}" --manifest "${normalized}" --json-source "${json_source}" ${baseline_args}
        COMMAND "${CMAKE_COMMAND}" -E touch "${stamp}"
        DEPENDS ${baseline_dep} "${schema}" "${schema_dir}/${native_header}" "${generator}"
        VERBATIM)
    add_custom_target(${REFLECT_TARGET}_generate DEPENDS "${stamp}")
    add_library(${REFLECT_TARGET} STATIC "${source}" "${json_source}")
    add_dependencies(${REFLECT_TARGET} ${REFLECT_TARGET}_generate)
    set_target_properties(${REFLECT_TARGET} PROPERTIES POSITION_INDEPENDENT_CODE ON
        CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
    target_include_directories(${REFLECT_TARGET} PUBLIC "${output_dir}" "${schema_dir}")
    target_link_libraries(${REFLECT_TARGET} PUBLIC Ludus::FoundationSerialization)
    target_compile_features(${REFLECT_TARGET} PUBLIC cxx_std_23)
    set_target_properties(${REFLECT_TARGET} PROPERTIES CXX_EXTENSIONS OFF)
    if(COMMAND ludus_apply_project_defaults)
        ludus_apply_project_defaults(${REFLECT_TARGET})
    else()
        ludus_apply_app_policy(${REFLECT_TARGET})
        if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options(${REFLECT_TARGET} PRIVATE -Wall -Wextra -Wpedantic -Werror)
        endif()
    endif()
endfunction()
