#pragma once

#include <ludus/foundation/base/config.h>
#include <ludus/foundation/base/types.h>

#include <span>
#include <string_view>

// The exported target fences the compiler's actual architecture as well as
// CMake admission. A consumer cannot silently mislabel a cross-compiled SDK.
#if defined(LUDUS_BEHAVIOR_EXPECTED_ARCH)
static_assert(LUDUS_TARGET_ARCH == LUDUS_BEHAVIOR_EXPECTED_ARCH, "Behavior SDK architecture mismatch");
#endif

namespace ludus::runtime::behavior
{
using namespace foundation;

/// Supported copied value kinds; no language object or native pointer is a value.
enum class Kind : uint8
{
    Uint32 = 1,  ///< Exact unsigned 32-bit integer.
    Boolean = 2, ///< Boolean; scalar representation is zero or one.
    Entity = 3,  ///< Generation-checked, execution-scoped entity reference.
};
/// Logical identity. The host checks world/session/execution and live slot/generation.
struct EntityRef
{
    uint64 World = 0;      ///< World identity, never a Luau number.
    uint64 Session = 0;    ///< Owning play session.
    uint64 Execution = 0;  ///< Owning provider generation.
    uint32 Slot = 0;       ///< Game-owned entity slot.
    uint32 Generation = 0; ///< Slot generation.
};
/// Tagged copied value; unused members must remain zero.
struct Value
{
    Kind Type = Kind::Uint32; ///< Active representation.
    uint32 Scalar = 0;        ///< Uint32 value or boolean zero/one.
    EntityRef Entity{};       ///< Entity representation when Type is Entity.
};
/// One stable field identity and its copied value.
struct Field
{
    uint32 Id = 0; ///< Nonzero schema field identity.
    Value Data{};  ///< Field value.
};
/// Bounded declared record. Only Items[0..Count) are meaningful.
struct Record
{
    Field Items[16] = {}; ///< Up to sixteen uniquely identified fields.
    uint32 Count = 0;     ///< Number of fields.
};
/// Immutable field descriptor. Names are ASCII identifiers, at most 63 bytes.
struct FieldSpec
{
    uint32 Id = 0;              ///< Stable nonzero field identity.
    const char* Name = nullptr; ///< Borrowed, null-terminated authoring name.
    Kind Type = Kind::Uint32;   ///< Required representation.
    uint32 Min = 0;             ///< Inclusive scalar lower bound; zero for Entity.
    uint32 Max = 0;             ///< Inclusive scalar upper bound; zero for Entity.
    uint32 Default = 0;         ///< Default declared scalar value; zero for Entity.
};
/// Named deferred operation. Execution only stages commands; the game applies them later.
struct Operation
{
    uint32 Id = 0;                        ///< Stable nonzero operation identity.
    const char* Name = nullptr;           ///< Borrowed ASCII identifier.
    uint32 Phase = 0;                     ///< Required game-defined phase identity.
    uint64 Capability = 0;                ///< Required bits in Invocation::Capabilities.
    std::span<const FieldSpec> Arguments; ///< Up to four checked arguments, in signature order.
};
/// Project-defined immutable contract generated by the paired host cooker.
struct Contract
{
    const char* Digest = nullptr; ///< Exactly 64 lowercase hex bytes plus terminator; integrity, not authentication.
    std::span<const FieldSpec> Config;     ///< Up to sixteen immutable configuration fields.
    std::span<const FieldSpec> State;      ///< One to sixteen declared scalar state fields; no Entity fields.
    std::span<const FieldSpec> Event;      ///< Up to sixteen event fields, including scoped entities.
    std::span<const Operation> Operations; ///< Up to sixteen deferred operations.
};
/// Context and copied inputs for one synchronous handler invocation.
struct Invocation
{
    uint64 Asset = 0;        ///< Cooked entrypoint asset identity.
    uint64 Revision = 0;     ///< Exact expected cooked revision.
    uint64 Instance = 0;     ///< Nonzero game-owned behavior instance identity.
    uint64 World = 0;        ///< Nonzero logical world identity.
    uint64 Session = 0;      ///< Nonzero owning session identity.
    uint64 Execution = 0;    ///< Nonzero execution generation.
    uint64 Tick = 0;         ///< Simulation tick, chosen by the game.
    uint32 Phase = 0;        ///< Current game-defined phase identity.
    uint64 Capabilities = 0; ///< Admitted operation capability bits.
    Record Config{};         ///< Values matching Contract::Config.
    Record State{};          ///< Published declared state matching Contract::State.
    Record Event{};          ///< Values matching Contract::Event.
};
/// Deferred command. Token is scoped to this invocation and never denotes a VM object.
struct Command
{
    uint32 Operation = 0;    ///< Contract operation identity.
    uint32 Token = 0;        ///< One-based request sequence within this invocation.
    Value Arguments[4] = {}; ///< Copied argument values.
    uint32 Count = 0;        ///< Number of arguments.
};
/// Explicit command admission result; rejection does not append a command.
enum class CommandStatus : uint8
{
    Accepted,          ///< Staged; the game has not applied the command yet.
    InvalidValue,      ///< Unknown operation, wrong arity/type or out-of-range value.
    InvalidEntity,     ///< Wrong world/session/execution or dead entity generation.
    InvalidPhase,      ///< Invocation is outside the operation's phase.
    MissingCapability, ///< Invocation lacks the required capability bits.
    CapacityExceeded,  ///< Sixteen commands are already staged.
};
/// Copied command admission result, shared by native and Luau behavior.
struct CommandResult
{
    CommandStatus Status = CommandStatus::InvalidValue; ///< Admission status.
    uint32 Token = 0;                                   ///< Nonzero only when accepted.
};
/// Complete unpublished invocation result. The owner publishes state/effects together.
struct Outcome
{
    Record State{};            ///< Candidate declared state.
    Command Commands[16] = {}; ///< Ordered staged commands.
    uint32 Count = 0;          ///< Number of staged commands.
};
/// Owner-thread service boundary. It must finish without entering a VM or mutating the world.
struct Services
{
    void* User = nullptr; ///< Borrowed native service context.
    bool (*IsAlive)(void*,
                    EntityRef) noexcept = nullptr; ///< Checks game-owned slot/generation; required for Entity values.
};
/// Synchronous provider result. Every failure preserves the caller's Outcome.
enum class Status : uint8
{
    Completed,         ///< A validated candidate outcome was copied to the caller.
    InvalidContract,   ///< Contract descriptors are invalid or unsupported.
    InvalidPackage,    ///< Trusted package layout, profile, contract or revision mismatch.
    InvalidInput,      ///< Identity or input record violates the contract.
    NotReady,          ///< No active package, or provider needs loading after a script fault.
    Reentrant,         ///< Nested invocation/load/close is forbidden.
    AllocationFailure, ///< Bounded provider/VM allocation failed.
    ScriptFault,       ///< Runtime error or invalid declared state; VM retired.
    Interrupted,       ///< Cooperative safepoint limit exceeded; VM retired.
    Paused,            ///< Debugger owns a partial invocation; no state/effects have published.
};
/// Copied bounded diagnostic. No VM object, traceback pointer or language value escapes.
struct Diagnostic
{
    Status Code = Status::Completed; ///< Provider status.
    uint32 Operation = 0;            ///< Last admitted/rejected native operation, if any.
    uint32 NativeStatus = 0;         ///< Last CommandStatus representation.
    char Message[192] = {};          ///< Truncated null-terminated runtime error.
};
/// Shared native/Luau staged transaction; construction is reserved to the provider functions.
class Transaction final
{
public:
    /// Mutable candidate state; validation runs before publication.
    [[nodiscard]] Record& State() noexcept;
    /// Read-only invocation inputs; valid only during the handler call.
    [[nodiscard]] const Invocation& Input() const noexcept;
    /// Stages a checked command; performs no world mutation, allocation or VM entry.
    [[nodiscard]] CommandResult Request(uint32 operation, std::span<const Value> arguments) noexcept;

private:
    friend class LuauProvider;
    friend Status ExecuteNative(const Contract&,
                                const Invocation&,
                                Services,
                                Status (*)(Transaction&, void*) noexcept,
                                void*,
                                Outcome&) noexcept;
    Transaction(const Contract& contract, const Invocation& input, Services services) noexcept;
    const Contract& mContract;
    const Invocation& mInput;
    Services mServices;
    Outcome mCandidate;
    uint32 mOperation = 0;
    uint32 mNativeStatus = 0;
};
/// Trusted native gameplay callback. Arbitrary C++ remains outside a sandbox.
using NativeHandler = Status (*)(Transaction&, void*) noexcept;
/// Executes a native callback through the same checked state/command contract.
/// @note Owner-thread only. Callback/services/context must outlive the call; output is preserved on failure.
[[nodiscard]] Status ExecuteNative(const Contract& contract,
                                   const Invocation& input,
                                   Services services,
                                   NativeHandler handler,
                                   void* user,
                                   Outcome& output) noexcept;
/// Exact reviewed runtime-profile fingerprint required by cooked packages (64 lowercase hex bytes).
[[nodiscard]] std::string_view LuauProfile() noexcept;
/// Encodes declared scalar state as bounded, versioned little-endian records with the contract digest.
/// @note Preserves output and written on failure. No native layout, entity or VM object is serialized.
[[nodiscard]] bool
EncodeState(const Contract& contract, const Record& state, std::span<uint8> output, usize& written) noexcept;
/// Decodes an exact-contract state record; rejects trailing bytes and preserves output on failure.
[[nodiscard]] bool DecodeState(const Contract& contract, std::span<const uint8> bytes, Record& output) noexcept;
/// Migrates scalar state by field ID; missing new fields use defaults, removed/changed/out-of-range fields fail.
/// @note Validates the source record's scalar representation and preserves output on failure; this is an explicit owner
/// policy.
[[nodiscard]] bool MigrateState(const Record& source, const Contract& target, Record& output) noexcept;
/// Explicit debugger resume policy; no gameplay coroutine or continuation is exposed.
enum class DebugMode : uint8
{
    Continue, ///< Run until the next breakpoint or completion.
    Into,     ///< Stop at the next executable source line.
    Over,     ///< Stop at the next line at the same or shallower call depth.
    Out,      ///< Stop after returning to the caller.
};
/// Bounded copied stack frame; source identifies a cooked asset, never a VM pointer.
struct DebugFrame
{
    char Source[96] = {};   ///< Truncated compiler source name.
    char Function[48] = {}; ///< Truncated function name.
    int32 Line = 0;         ///< Compiled source line, mapped through cook evidence.
};
/// Safe local inspection. Objects remain opaque; strings contain at most 64 bytes in hex.
struct DebugLocal
{
    char Name[48] = {};     ///< Truncated local name.
    uint8 Kind = 0;         ///< Nil, boolean, number, string bytes, opaque, nonfinite (0..5).
    float64 Number = 0;     ///< Finite numeric value when Kind is 2.
    bool Boolean = false;   ///< Boolean value when Kind is 1.
    char Bytes[129] = {};   ///< Hex string bytes when Kind is 3; no getters are invoked.
    bool Truncated = false; ///< Value exceeded its copied budget.
};
/// Owner-thread debugger snapshot. No evaluation, object traversal or VM references.
struct DebugSnapshot
{
    DebugFrame Frames[8] = {};  ///< Top eight stack frames.
    DebugLocal Locals[16] = {}; ///< First sixteen locals.
    uint32 FrameCount = 0;      ///< Number of copied frames.
    uint32 LocalCount = 0;      ///< Number of copied locals.
    uint64 Stop = 0;            ///< Exact pause identity across loads of this owner, required by ResumeDebug.
    bool Paused = false;        ///< An invocation remains unpublished.
    bool Truncated = false;     ///< Stack or locals exceeded the copy budget.
};
/// Owner-thread interpreter provider with an implementation-only VM and fallible allocation.
/// @note Owner-thread only, no concurrent access. Does not cross the GameApi ABI or own world state.
class LuauProvider final
{
public:
    /// Constructs an unloaded provider without allocating.
    LuauProvider() noexcept = default;
    /// Retires the VM. Destruction inside its callback is a contract violation.
    ~LuauProvider() noexcept;
    /// Providers cannot share or copy VM ownership.
    LuauProvider(const LuauProvider&) = delete;
    /// Providers cannot assign VM ownership.
    LuauProvider& operator=(const LuauProvider&) = delete;
    /// Stages a fresh VM and retains the active package if preparation fails.
    /// @param contract Borrowed immutable generated descriptor and strings; must outlive the active VM.
    /// @param trusted_package Only accepted paired-cooker bytes, admitted by the owner; never hostile bytecode.
    /// @param heap_limit Per-VM peak allocator byte limit, including temporary realloc storage; nonzero.
    /// @note Reload can hold old/new VMs simultaneously; fixed provider metadata is outside this limit.
    /// @param safepoints Cooperative invocation/initialization bound; nonzero, not an instruction count.
    /// @note Contract and immutable package storage must outlive the active VM. No acquisition/download occurs.
    /// A partial invocation returns Paused; complete or Close it before replacing this package.
    [[nodiscard]] Status Load(const Contract& contract,
                              std::span<const uint8> trusted_package,
                              usize heap_limit = usize{8} * 1024 * 1024,
                              uint32 safepoints = 100000) noexcept;
    /// Runs one non-yielding handler; validates all copied inputs/state and preserves output on failure.
    /// @note A runtime fault retires this VM; explicit Load is required to resume play. Services are borrowed only for
    /// the call.
    [[nodiscard]] Status
    Invoke(const Invocation& input, Services services, Outcome& output, Diagnostic& diagnostic) noexcept;
    /// Begins an explicitly debug-enabled invocation, retaining copied inputs and staged state until completion.
    /// @note Services::User must outlive any pause. The owning game must stop simulation until completion or Close.
    /// Output is preserved while paused or on failure; debugger storage is fallibly allocated outside hot paths.
    [[nodiscard]] Status
    BeginDebug(const Invocation& input, Services services, Outcome& output, Diagnostic& diagnostic) noexcept;
    /// Resumes exactly the inspected pause. Stale/zero stops fail without entering the VM or changing output.
    [[nodiscard]] Status
    ResumeDebug(uint64 expected_stop, DebugMode mode, Outcome& output, Diagnostic& diagnostic) noexcept;
    /// Configures an asset breakpoint at a compiled line; returns the actual executable line, or -1 on rejection.
    [[nodiscard]] int32 Breakpoint(uint64 asset, int32 compiled_line, bool enabled = true) noexcept;
    /// Copies safe stack/local values; preserves output on reentrancy or when no package is loaded.
    [[nodiscard]] bool Inspect(DebugSnapshot& output) const noexcept;
    /// Retires the VM and any partial debugger transaction. A nested call returns Reentrant and leaves ownership
    /// intact.
    [[nodiscard]] Status Close() noexcept;
    /// Returns physical VM allocation bytes, including headers/retained capacity
    /// (zero when unloaded); excludes fixed owner metadata.
    [[nodiscard]] usize LiveBytes() const noexcept;

private:
    [[nodiscard]] Status FinishDebug(Diagnostic& diagnostic, Outcome& output) noexcept;
    struct Impl;
    Impl* mImpl = nullptr;
    uint64 mNextStop = 0;
};
} // namespace ludus::runtime::behavior
